config/routes.rb
Betyouimright::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :bonuses

  resources :notifications

  resources :bet_categories

  resources :authentications

  resources :categories
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  match '/bets/feed', :controller => 'bets', :action => 'feed', :format => 'atom'
  match '/users/:user_id/publicprofile' => 'users#publicprofile', :as => :publicprofile
  match '/users/index' => 'users#index', :as => "users"
  match '/users/friends' => 'users#friends', :as => "userfriends"
  match '/users/:id/toggleadmin' => 'users#toggleadmin', :as => :toggleadmin
  match '/wagers/my_wagers' => 'wagers#my_wagers', :as => :my_wagers
  match '/bets/my_bets' => 'bets#my_bets', :as => :my_bets
  
  resources :comments do
    resources :comments
    get 'cancel'
    get 'cancel_new'
  end
  
  resources :cashouts, :except => [:show, :edit] 

  resources :purchases, :except => [:edit] do
    get 'payment_info'
  end  

  resources :payment_notifications
  
  resources :wallets, :only => [:show] do
    get 'editname'
    get 'updatename'
    get 'cancelname'
  end  

  resources :bets do
    collection do
        get 'search'
        get 'public'
        get 'private'
    end
    member do
        get 'won', :as => "won"
        get 'lost', :as => "lost"
    end
    resources :wagers, :except => [:index, :show, :create, :new, :destroy]
    resources :comments
  end  

  resources :transactions, :only => [:index]
  resources :bragging, :only => [:index]
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/sign_out' => 'users#destroy'
  end
    
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/users/logout' => 'users#logout', :as => "logout"
  match '/transactions/my_transactions' => 'transactions#my_transactions', :as => :my_transactions
  match '/bets/:bet_id/comments/cancel' => 'comments#cancel', :as => :cancel_bet_comment
  match '/bets/:bet_id/wagers/:against' => 'wagers#bet_now', :as => :bet_now
  match '/sitemap', :controller => 'sitemaps', :action => 'index', :format => 'xml'
  match '/:action' => 'static#:action'
  match '/javascripts/:action.:format', :controller => 'javascripts'
  match '/bets/:id' => 'bets#show', :via => [:get, :post]
  constraints(Subdomain) do  
      match '/' => 'forums#show', :via => :get  
    end
  root :to => "bets#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title, :message, :user_id, :viewed, :closed
  scope :default, :order => "created_at DESC", :conditions => ["closed = ?", false]
  scope :top5, default.limit(5)  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_admin
  
  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(params[:notification])
    if @notification.save
      redirect_to @notification, :notice => "Successfully created notification."
    else
      render :action => 'new'
    end
  end

  def edit
    @notification = Notification.find(params[:id])
  end

  def update
    @notification = Notification.find(params[:id])
    if @notification.update_attributes(params[:notification])
      redirect_to @notification, :notice  => "Successfully updated notification."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_to notifications_url, :notice => "Successfully destroyed notification."
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
  def create_notifications
    messages = ""
    if user_signed_in?
      unless current_user.notifications.top5.empty?
        messages += "<div id='notifications'><div id='notifications-button'><div class='down-arrow'></div><div class='notifications-button-text'>You have #{pluralize(current_user.notifications.top5.count, 'unread notification')}</div></div><div id='notifications-wrapper'>"
        current_user.notifications.top5.each do |notification|
          messagebody = truncate(notification.title, :length =>55) + "<div class='close-link'>#{link_to 'X', '/javascripts/close_link.js?notification='+ notification.id.to_s, :title => 'Remove', :remote => true}</div>" + (content_tag :div, raw(notification.message), :id => "notification-#{notification.id}-message", :class => "notification-message")
          messages += content_tag :div, raw(messagebody), :id => "notification-#{notification.id}", :class => "notification", "data-tooltip" => notification.message
        end
        messages += "</div></div>"
      end
    end
    return raw(messages)
  end
  
end

app/views/notifications/_form.html.erb
<%= semantic_form_for @notification do |f| %>
  <%= error_div_for @notification %>
  <%= error_messages_for(@notification)  %>
  <%= f.inputs do %>
	<%= f.input :title, :input_html => { :placeholder => "e.g You won a new award" } %>
	<%= f.input :message, :input_html => { :rows => 10, :cols => 10, :maxlength => 500, :placeholder => "e.g You won an award to betting correctly against over more than 20 people, with no one betting with you" } %>
	<%= f.input :user_id, :collection => User.all, :include_blank => false  %>
	<%= f.input :viewed %>
	<%= f.input :closed %>	
  <% end %>	
  <%= f.buttons %>
<% end %>

app/views/notifications/edit.html.erb
<% title "Edit Notification" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @notification %> |
  <%= link_to "View All", notifications_path %>
</p>

app/views/notifications/index.html.erb
<% title "Notifications" %>

<table>
  <tr>
    <th>Title</th>
    <th>Message</th>
    <th>User</th>
    <th>Viewed</th>
    <th>Closed</th>
  </tr>
  <% for notification in @notifications %>
    <tr>
      <td><%= notification.title %></td>
      <td><%= notification.message %></td>
      <td><%= notification.user_id %></td>
      <td><%= notification.viewed %></td>
      <td><%= notification.closed %></td>
      <td><%= link_to "Show", notification %></td>
      <td><%= link_to "Edit", edit_notification_path(notification) %></td>
      <td><%= link_to "Destroy", notification, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Notification", new_notification_path %></p>

app/views/notifications/new.html.erb
<% title "New Notification" %>

<%= render 'form' %>

<p><%= link_to "Back to List", notifications_path %></p>

app/views/notifications/show.html.erb
<% title "Notification" %>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>
<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>
<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>
<p>
  <strong>Viewed:</strong>
  <%= @notification.viewed %>
</p>
<p>
  <strong>Closed:</strong>
  <%= @notification.closed %>
</p>

<p>
  <%= link_to "Edit", edit_notification_path(@notification) %> |
  <%= link_to "Destroy", @notification, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", notifications_path %>
</p>