config/routes.rb
Betyouimright::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :bonuses

  resources :notifications

  resources :bet_categories

  resources :authentications

  resources :categories
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  match '/bets/feed', :controller => 'bets', :action => 'feed', :format => 'atom'
  match '/users/:user_id/publicprofile' => 'users#publicprofile', :as => :publicprofile
  match '/users/index' => 'users#index', :as => "users"
  match '/users/friends' => 'users#friends', :as => "userfriends"
  match '/users/:id/toggleadmin' => 'users#toggleadmin', :as => :toggleadmin
  match '/wagers/my_wagers' => 'wagers#my_wagers', :as => :my_wagers
  match '/bets/my_bets' => 'bets#my_bets', :as => :my_bets
  
  resources :comments do
    resources :comments
    get 'cancel'
    get 'cancel_new'
  end
  
  resources :cashouts, :except => [:show, :edit] 

  resources :purchases, :except => [:edit] do
    get 'payment_info'
  end  

  resources :payment_notifications
  
  resources :wallets, :only => [:show] do
    get 'editname'
    get 'updatename'
    get 'cancelname'
  end  

  resources :bets do
    collection do
        get 'search'
        get 'public'
        get 'private'
    end
    member do
        get 'won', :as => "won"
        get 'lost', :as => "lost"
    end
    resources :wagers, :except => [:index, :show, :create, :new, :destroy]
    resources :comments
  end  

  resources :transactions, :only => [:index]
  resources :bragging, :only => [:index]
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/sign_out' => 'users#destroy'
  end
    
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/users/logout' => 'users#logout', :as => "logout"
  match '/transactions/my_transactions' => 'transactions#my_transactions', :as => :my_transactions
  match '/bets/:bet_id/comments/cancel' => 'comments#cancel', :as => :cancel_bet_comment
  match '/bets/:bet_id/wagers/:against' => 'wagers#bet_now', :as => :bet_now
  match '/sitemap', :controller => 'sitemaps', :action => 'index', :format => 'xml'
  match '/:action' => 'static#:action'
  match '/javascripts/:action.:format', :controller => 'javascripts'
  match '/bets/:id' => 'bets#show', :via => [:get, :post]
  constraints(Subdomain) do  
      match '/' => 'forums#show', :via => :get  
    end
  root :to => "bets#index"

end

app/views/shared/_admin-links.html.erb
<div class="infobox-container infobox-admin opaque"> 
	<div class="triangle-l"></div> 
	<div class="triangle-r"></div> 

	<div class="infobox"> 
		<h3><span>Admin Links</span></h3> 
		<ul>
			<li><%= link_to "All Purchases", purchases_url(:subdomain => false) %></li>
			<li><%= link_to "All Cashouts", cashouts_url(:subdomain => false) %></li>
			<li><%= link_to "Create a new Category", new_bet_category_path(:subdomain => false) %></li>
		</ul>	
	</div> 
</div>

app/views/shared/_bragging.html.erb
<% cache("bragging", :expires_in => 1.day) do %>
	<div class="standard-padding brag-panel">
		<div class="brag-panel-name heading">Name</div><div class="brag-panel-score heading">Score</div>
		<% User.top10.each_with_index do |user, index| %>
			<div class="brag-panel-name"><%= index + 1 %>. <%= user.display_name %></div><div class="brag-panel-score"><%= user.wallet.score %> points</div>
		<% end %>
	</div>	
<% end %>

app/views/shared/_friends_list.fb.erb
<div id="friends-list" class="friends">
	<% if user_signed_in? %>
	<h3>Your friends</h3>
	<ul>
		<% current_user.friends.by_scores.limit(5).each do |user| %>
			<li><%= link_to image_tag(user.profile, :alt => user.display_name, :width => 30, :height => 30) + user.display_name, publicprofile_path(user), :title => user.display_name  %></li>
		<% end %>
	</ul>	
	<% end %>
</div>

app/views/shared/_friends_list.html.erb
<div id="container-right" class="">
	<% if user_signed_in? %>
	<div class="image-gallery">
		<h3>Your friends</h3>
		<% current_user.friends.limit(10).each do |user| %>
			<div class="image-gallery-photo small-zoom"><%= link_to image_tag(user.profile, :alt => user.display_name), publicprofile_path(user), :title => user.display_name %></div>
		<% end %>
	</div>
	<% else %>
		<fb:facepile href="<%= root_url(:subdomain => false) %>" width="200" max_rows="20"></fb:facepile>
	<% end %>
</div>	

app/views/shared/_login.fb.erb
<div id="user_nav">
	<% if user_signed_in? %>
		<div id="credit-nav" class="left">
      		<div class='credit-nav-link'><%= create_credits_html %></div>
			<div>
				<a href="<%= url_for current_user.wallet %>" title="<%= distance_of_time_in_words(Time.now, current_user.wallet.pointtime) %>">
					<div class="points-outer">
			  			<div class="left points-inner" style="width:<%= current_user.wallet.rel_time_to_more_credits %>px;"></div>
					<div class="points-text very-small-text italics">Time till next free credit</div>
			  		</div>
				</a>
			</div>
		</div>
		<div class="left separator"></div><!-- Signed in as <%= current_user.email %>. Not you? -->
		<div id="login-nav" class="left">
      		<%= link_to "Sign out", logout_path, :title => "Signed in as " + current_user.display_name %>
		</div>
    <% else %>
		<div id="login-nav" class="left">
			<%= link_to "Sign in", user_omniauth_authorize_path(:facebookcanvas) %>
		</div>
    <% end %>
</div>

app/views/shared/_login.html.erb
<div id="user_nav">
	<% if user_signed_in? %>
		<div id="credit-nav" class="left">
      		<div class='credit-nav-link'><%= create_credits_html %></div>
			<div>
				<a href="<%= url_for current_user.wallet %>" title="<%= distance_of_time_in_words(Time.now, current_user.wallet.pointtime) %>">
					<div class="points-outer">
			  			<div class="left points-inner" style="width:<%= current_user.wallet.rel_time_to_more_credits %>px;"></div>
					<div class="points-text very-small-text italics">Time till next free credit</div>
			  		</div>
				</a>
			</div>
		</div>
		<div class="left separator"></div><!-- Signed in as <%= current_user.email %>. Not you? -->
		<div id="login-nav" class="left">
      		<%= link_to "Sign out", logout_path, :title => "Signed in as " + current_user.display_name %>
		</div>
    <% else %>
		<div id="login-nav" class="left">
			<%= link_to "Sign in", user_omniauth_authorize_path(:facebook) %>
		</div>
    <% end %>
</div>

app/views/shared/_mystats.fb.erb
<div>
	<h3>My Ranking</h3>
	<% if user_signed_in? %>
		<% cache("mystats-" + current_user.id.to_s, :expires_in => 1.day) do %>
			You are currently ranked <%= current_user.rank.ordinalize %> with <%= current_user.wallet.score %> points
		<% end %>
		<p>
			<%= link_to "My Account", current_user.wallet(:subdomain => false), :title => "View Account", :class => "fb-fancybox" %>
		</p>
	<% else %>
	You need to <%= link_to "Sign in", 'auth/facebook' %> to see your ranking and score
	<% end %>
</div>

app/views/shared/_mystats.html.erb
<div>
	<h3>My Ranking</h3>
	<% if user_signed_in? %>
		<% cache("mystats-" + current_user.id.to_s, :expires_in => 1.day) do %>
			You are currently ranked <%= current_user.rank.ordinalize %> with <%= current_user.wallet.score %> points
		<% end %>
		<p>
			<%= link_to "My Account", current_user.wallet(:subdomain => false), :title => "View Account" %>
		</p>
	<% else %>
	You need to <%= link_to "Sign in", user_session_url(:subdomain => false) %> to see your ranking and score
	<% end %>
</div>

app/views/shared/_top_categories.fb.erb
<% cache("fb-top-bet-categories", :expires_in => 1.day) do %>
	<div class="left top-categories">
		<div class="center top-categories-title">Categories</div>
		<div class="clear"></div>	
			<% for bet_category in BetCategory.order("id ASC").limit(4) %>
				<div class="top-category-link left">
					<%= link_to bet_category.name, bet_category, :remote => true %> 
				</div>
			<% end %>
			<div class="top-category-link left">
				<%= link_to "All >>", bet_categories_path, :class => "fb-fancybox" %>
			</div>	
		
		<div class="clear"></div>	
	</div>	
<% end %>

app/views/shared/_top_categories.html.erb
<% cache("top-bet-categories", :expires_in => 1.day) do %>
	<div class="left top-categories">
		<div class="center top-categories-title">Categories</div>
		<div class="clear"></div>	
			<% for bet_category in BetCategory.order("id ASC").limit(4) %>
				<div class="top-category-link left">
					<%= link_to bet_category.name, bet_category %> 
				</div>
			<% end %>
			<div class="top-category-link left">
				<%= link_to "All >>", bet_categories_path %>
			</div>	
		
		<div class="clear"></div>	
	</div>	
<% end %>

app/views/shared/show_notice.js.erb
$("#container").prepend('<%= escape_javascript(create_flash_messages(flash, true)) %></div>');
window.scrollTo(0,0);
flashNotice();

app/views/shared/validation_error.js.erb
if ($('#errors_for_<%= escape_javascript(@model.class.name.underscore) %>').length > 0)
{
	$('#errors_for_<%= escape_javascript(@model.class.name.underscore) %>').html('<%= escape_javascript(raw(@model.errors.collect{|k,v| "<li>The #{k} field #{v}</li>"}.to_s )) %> </ul>')
	$('#errors_for_<%= escape_javascript(@model.class.name.underscore) %>').addClass('error_messages')
	$('#errors_for_<%= escape_javascript(@model.class.name.underscore) %>').effect("highlight", {}, 3000);
}
$('.inline-errors').remove();
<% @model.errors.each do |attr,msg| %>
	<% if attr.to_s == "errors" %>
		$("#errors").append("<p class='inline-errors'><%= msg %></p>");
	<% else %>
		$('li#<%= escape_javascript(@model.class.name.underscore) %>_<%= attr.to_s %>_input').append("<p class='inline-errors'><%= msg %></p>");
	<% end  %>
<% end %>	