config/routes.rb
Betyouimright::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :bonuses

  resources :notifications

  resources :bet_categories

  resources :authentications

  resources :categories
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  match '/bets/feed', :controller => 'bets', :action => 'feed', :format => 'atom'
  match '/users/:user_id/publicprofile' => 'users#publicprofile', :as => :publicprofile
  match '/users/index' => 'users#index', :as => "users"
  match '/users/friends' => 'users#friends', :as => "userfriends"
  match '/users/:id/toggleadmin' => 'users#toggleadmin', :as => :toggleadmin
  match '/wagers/my_wagers' => 'wagers#my_wagers', :as => :my_wagers
  match '/bets/my_bets' => 'bets#my_bets', :as => :my_bets
  
  resources :comments do
    resources :comments
    get 'cancel'
    get 'cancel_new'
  end
  
  resources :cashouts, :except => [:show, :edit] 

  resources :purchases, :except => [:edit] do
    get 'payment_info'
  end  

  resources :payment_notifications
  
  resources :wallets, :only => [:show] do
    get 'editname'
    get 'updatename'
    get 'cancelname'
  end  

  resources :bets do
    collection do
        get 'search'
        get 'public'
        get 'private'
    end
    member do
        get 'won', :as => "won"
        get 'lost', :as => "lost"
    end
    resources :wagers, :except => [:index, :show, :create, :new, :destroy]
    resources :comments
  end  

  resources :transactions, :only => [:index]
  resources :bragging, :only => [:index]
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/sign_out' => 'users#destroy'
  end
    
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/users/logout' => 'users#logout', :as => "logout"
  match '/transactions/my_transactions' => 'transactions#my_transactions', :as => :my_transactions
  match '/bets/:bet_id/comments/cancel' => 'comments#cancel', :as => :cancel_bet_comment
  match '/bets/:bet_id/wagers/:against' => 'wagers#bet_now', :as => :bet_now
  match '/sitemap', :controller => 'sitemaps', :action => 'index', :format => 'xml'
  match '/:action' => 'static#:action'
  match '/javascripts/:action.:format', :controller => 'javascripts'
  match '/bets/:id' => 'bets#show', :via => [:get, :post]
  constraints(Subdomain) do  
      match '/' => 'forums#show', :via => :get  
    end
  root :to => "bets#index"

end

app/controllers/bonuses_controller.rb
class BonusesController < ApplicationController
  before_filter :authenticate_admin
  
  def index
    @bonuses = Bonus.all
  end

  def show
    @bonus = Bonus.find(params[:id])
  end

  def new
    @bonus = Bonus.new
  end

  def create
    @bonus = Bonus.new(params[:bonus])
    if @bonus.save
      redirect_to @bonus, :notice => "Successfully created bonus."
    else
      render :action => 'new'
    end
  end

  def edit
    @bonus = Bonus.find(params[:id])
  end

  def update
    @bonus = Bonus.find(params[:id])
    if @bonus.update_attributes(params[:bonus])
      redirect_to @bonus, :notice  => "Successfully updated bonus."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @bonus = Bonus.find(params[:id])
    @bonus.destroy
    redirect_to bonuses_url, :notice => "Successfully destroyed bonus."
  end
end

app/helpers/bonuses_helper.rb
module BonusesHelper
  
  def short_status(status)
    if status == "Activated"
      "activated"
    else
      "nothing"
    end
  end
  
end

app/views/bonuses/_form.html.erb
<%= semantic_form_for @bonus do |f| %>
  <%= error_div_for @bonus %>
  <%= error_messages_for(@bonus)  %>
  <%= f.inputs do %>
	<%= f.input :name, :input_html => { :placeholder => "e.g Go Big or Go Home" } %>
	<%= f.input :short_description, :input_html => { :placeholder => "e.g 5 extra credits for a brave bet" } %>
	<%= f.input :description, :input_html => { :rows => 10, :cols => 10, :maxlength => 500, :placeholder => "e.g If the bet creator wins a bet where the losers outnumber the winners by a factor of 10, he wins an extra 5 credits" } %>
	<%= f.input :rule %>
	<%= f.input :rule_description %>
	<%= f.input :bonustype, :as => :select, :collection => Bonus.bonus_types, :include_blank => false  %>
	<%= f.input :activation, :as => :select, :collection => Bonus.activation_types, :include_blank => false  %>
	<%= f.input :credits %>
	<%= f.input :target %>
	<%= f.input :beneficiary, :as => :select, :collection => Bonus.beneficiary_types, :include_blank => false  %>
  <% end %>	
  <%= f.buttons %>
<% end %>

app/views/bonuses/edit.html.erb
<% title "Edit Bonus" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @bonus %> |
  <%= link_to "View All", bonuses_path %>
</p>

app/views/bonuses/index.html.erb
<% title "Bonuses" %>

<table>
  <tr>
    <th>Name</th>
    <th>Short Description</th>
    <th>Description</th>
    <th>Rule</th>
    <th>Rule Description</th>
    <th>Activation</th>
  </tr>
  <% for bonus in @bonuses %>
    <tr>
      <td><%= bonus.name %></td>
      <td><%= bonus.short_description %></td>
      <td><%= bonus.description %></td>
      <td><%= bonus.rule %></td>
      <td><%= bonus.rule_description %></td>
      <td><%= bonus.activation %></td>
      <td><%= link_to "Show", bonus %></td>
      <td><%= link_to "Edit", edit_bonus_path(bonus) %></td>
      <td><%= link_to "Destroy", bonus, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Bonus", new_bonus_path %></p>

app/views/bonuses/new.html.erb
<% title "New Bonus" %>

<%= render 'form' %>

<p><%= link_to "Back to List", bonuses_path %></p>

app/views/bonuses/show.html.erb
<% title "Bonus" %>

<p>
  <strong>Name:</strong>
  <%= @bonus.name %>
</p>
<p>
  <strong>Short Description:</strong>
  <%= @bonus.short_description %>
</p>
<p>
  <strong>Description:</strong>
  <%= @bonus.description %>
</p>
<p>
  <strong>Rule:</strong>
  <%= @bonus.rule %>
</p>
<p>
  <strong>Rule Description:</strong>
  <%= @bonus.rule_description %>
</p>
<p>
  <strong>Type of Bonus:</strong>
  <%= @bonus.bonustype %>
</p>
<p>
  <strong>Activation:</strong>
  <%= @bonus.activation %>
</p>
<p>
  <strong>Credits:</strong>
  <%= @bonus.credits %>
</p>
<p>
  <strong>Target:</strong>
  <%= @bonus.target %>
</p>
<p>
  <strong>Beneficiary:</strong>
  <%= @bonus.beneficiary %>
</p>

<p>
  <%= link_to "Edit", edit_bonus_path(@bonus) %> |
  <%= link_to "Destroy", @bonus, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", bonuses_path %>
</p>